### ISSUE TITLE
Script error

### ISSUE THREAD

**Issue by MegaKaktusDK** [SamMackrill/InDUstrious#1]
Getting script errors when activating all boards. :)

**Comment by SamMackrill** [comment]
Ha ha I haven't really released this yet :) Also just moving to Madis. Need to setup again. If you open the board does it tell you what the error is?

**Comment by MegaKaktusDK** [comment]
i havent looked to much at it, i would love getting this to work tho.. :D, ill try again later today on madis ;)

**Comment by IxionAlpha** [comment]
Hi
I solved some minor json errors. However, there is one in the display driver config I cannot fix:
attampt to get a nil value (field'getElementIDList') line 132 in start().

**Comment by MegaKaktusDK** [comment]
awww..  and that error will render the script useless?


Den søn. 1. nov. 2020 kl. 16.13 skrev IxionAlpha <notifications@github.com>:

**Comment by IxionAlpha** [comment]
Yes.
You have an idea? Sorry, I am new to this.

**Comment by SamMackrill** [comment]
Just making a new release

**Comment by MegaKaktusDK** [comment]
Seems better now, im stil not getting output to my medium screens.. Do they need to be large?

**Comment by SamMackrill** [comment]
I have not tried mediums yet. Will give it a go.

**Comment by MegaKaktusDK** [comment]
Whats your discord name?, :D

Den lør. 7. nov. 2020 kl. 20.49 skrev Sam Mackrill <notifications@github.com

**Comment by SamMackrill** [comment]
Smacker#5268

**Comment by SamMackrill** [comment]
Closing as the script error is fixed
