### ISSUE TITLE
Blank screens

### ISSUE THREAD

**Issue by GEEKsogen** [SamMackrill/InDUstrious#3]
I connected 6 Refiners M for testing. But only one is displayed on the screen. Did I make the correct circuit?
![6ae1ae91f95a8532c8123a08ff45c020](https://user-images.githubusercontent.com/42843783/99309801-d126c700-287b-11eb-8f51-0fcf17686150.png)

**Comment by SamMackrill** [comment]
Looks right, machines running normally are not shown. Just things you potentially need to deal with. I am guessing the others are all running fine.

**Comment by SamMackrill** [comment]
I am going to add a count of the industries running/stopped/pending. This should make it more obvious
