### ISSUE TITLE
CPU Overload

### ISSUE THREAD

**Issue by SamMackrill** [SamMackrill/InDUstrious#5]
Fix the CPU overload issue when starting-up boards

**Comment by cmacnichol** [comment]
@SamMackrill Anything that can be done to fix this temporarily?  My master board has started doing this and I cannot seem to get it working again at all.

**Comment by TheGeek007** [comment]
I too am having the CPU overload issue. As far as I can tell, when the code gets to the point of trying to index the components from the core, it tries to do it too quickly, causing a CPU overload. Granted my factory is 4000+ components, and thats not helping. I know that Dimencia's HUD uses coroutine.create() and coroutine.yield() to combat this problem. I wonder if this script would benefit from these functions?

**Comment by SamMackrill** [comment]
This should be fixed with V2
