### ISSUE TITLE
Minor adjustments to T3/4 alloy deployment

### ISSUE THREAD

**Issue by Tional** [SamMackrill/InDUstrious#9]
After my changes:
![image](https://user-images.githubusercontent.com/78389121/106857806-b00d8f80-668e-11eb-8257-53b3773373db.png)

Changes (snippet):
al={Headers={\"T1/2 Alloys\",\"T1/2 Alloys\"},Rows={{\"Silumin\",\"Duralumin\"},{\"AlFe\",\"CaRefCu\"},{\"Steel\",\"Stainless steel\"},{\"AlLi\",\"Inconel\"},{\"CuAg\",\"Maraging steel\"},{\"Red gold\",\"ScAl\"}}},a1={Headers={\"T1/2 Alloys\",\"T1/2 Alloys\"},Rows={{\"Silumin\",\"Duralumin\"},{\"AlFe\",\"CaRefCu\"},{\"Steel\",\"Stainless steel\"}}},a2={Headers={\"T3/4 Alloys\",\"T3/4 Alloys\"}

Required change to Lua Parameters in order to display, and fit, the T3/T4 alloys on 2 large transparent screens:

Display Blocks: "t5 t4 gl pl a1 a2 t3 t2 t1 ga"
ContRowsPerScreen: 22

**Comment by SamMackrill** [comment]
Much better! Sorry I didn't put a lot of thought into that :)
Missing the a2 substance lines but I can work that out

**Comment by Tional** [comment]
I didn't have to change those, just the headers.
